### ISSUE TITLE
Pages don't load if google tag manager is blocked (e.g. by an adblocker)

### ISSUE THREAD

**Issue by salcock** [InetIntel/ioda-ui#11]
Google Tag manager is built into our main IODA.js file, but some adblocking software will block requests to www.googletagmanager.com.

If this is blocked, then the javascript crashes and any IODA page will fail to render (i.e. get stuck on the "Loading" screen).

More details from the affected user:

````
ioda.3c9aca08.js:36 GA4React intialization failed: {"type":"error"}
    at HTMLScriptElement.i.onerror (https://ioda.inetintel.cc.gatech.edu/build/ioda.3c9aca08.js:36:28871)

ioda.3c9aca08.js:36 Uncaught (in promise) GA4React intialization failed: {"type":"error"}
    at HTMLScriptElement.i.onerror (https://ioda.inetintel.cc.gatech.edu/build/ioda.3c9aca08.js:36:28871)
````

````
GET https://www.googletagmanager.com/gtag/js?id=G-XD5MWMBCF9 net::ERR_BLOCKED_BY_CLIENT
o @ ioda.3c9aca08.js:36
````

**Comment by salcock** [comment]
Resolved.
